### ISSUE TITLE
Add an option to do not create a folder for each single file

### ISSUE THREAD

**Issue by gubo97000** [toto04/webeep-sync#23]
It's pretty annoying that each file has it's own folder, so an option to remove this behavior would be welcomed; 
it's also more consistent with the presentation of the actual folder in webeep.

Right now:
![image](https://user-images.githubusercontent.com/23000960/156931717-11b60c04-90c2-4aac-a761-d72b56b8296e.png)
Wanted behavior: 
![image](https://user-images.githubusercontent.com/23000960/156931760-7f975809-9f2b-47e9-8481-ee7f0f2c0727.png)

**Comment by toto04** [comment]
Thanks for the suggestion!
The current behavior comes from the general interpretation of how the Moodle API returns information about files in a course. Basically it turns out that top level single files like those are still shown as inside a folder (or module as they call them in the API) with a single file inside, and on webeep the actual file name is never shown, just the "folder" name.
I'll definitely add a special case in the next update to handle this to make the app's behavior more similar to the website's.
