### ISSUE TITLE
Il progamma crea una cartella corrotta non accessibile

### ISSUE THREAD

**Issue by mind-overflow** [toto04/webeep-sync#24]
Ciao! Creo un veloce bug report.  
Ho installato WeBeep Sync per salvarmi i documenti di tutti i corsi, ed è un aiuto immenso, quindi ottimo lavoro!
Purtroppo però c'è un corso che mi dà problemi. La struttura della cartella è questa:
```
Dispense
Esercitazioni A1 21-22 NomeProfessore A.
Esercizi
Esiti delle prove scritte
Pdf Esercitazioni Professore2
Programmi
Temi d'esame 2021-22
Temi d'esame anni precedenti
```

Il problema è questo: il programma crea tutte queste cartelle e inizia a scaricarci dentro i file. Purtroppo però, una di queste cartelle risulta corrotta; in particolare quella che si chiama `Esercitazioni A1 21-22 NomeProfessore A.`. Infatti il programma, dopo averla creata, inizia a scaricare i contenuti senza problemi, ma la cartella risulta inaccessibile. Ho provato su 3 pc diversi e il problema è identico su tutti. Quando provo ad aprirla, explorer mi restituisce questo errore:  
![immagine](https://i.ibb.co/1KhWjxr/Senzanome.png)  
  
Approfondendo, la cartella non si può eliminare, rinominare, spostare... Insomma non si può fare nulla: l'unico modo per eliminarla è avviare Linux, montare il filesystem NTFS da lì, e finalmente forzare l'eliminazione (il che risulta più complicato su un PC in particolare che è protetto da BitLocker). Infatti ho provato ad eliminarla tramite cmd, powershell, anche cygwin, ma nulla da fare. , Nemmeno chkdsk riconosce l'errore (solitamente becca le cartelle corrotte e chiede esplicitamente "cartella corrotta irrecuperabile, vuoi convertirla in file nullo?").  
Però, ho un'ipotesi: credo che il problema sia dato dal fatto che il nome della cartella termina con un punto. Infatti, nel messaggio d'errore che ho allegato, non compare il punto alla fine del nome, cosa che invece dovrebbe succedere - allora ha senso pensare che quella cartella non esiste, dato che effettivamente nel nome ha il punto. Investigando, con i numerosi comandi che ho provato da shell, mi è capitato più volte di incorrere in altri errori del tipo "file non accessibile" o "questa non è una cartella", il che mi fa pensare che il problema sia effettivamente di corruzione: il sistema non riesce bene a distinguere se questo sia un file o una cartella, e quindi non lo gestisce in nessuno dei due modi. Penso che il punto alla fine crei un bug in WeBeep Sync per quanto riguarda l'estensione dei file, e quindi crea una specie di ibrido tra cartella/file senza estensione/file nullo.  
  
In ogni caso, grazie mille per l'ottimo lavoro, e spero non sia troppo complicato da sistemare!

**Comment by mind-overflow** [comment]
Update: da Linux fino ad ora mi ero solo limitato ad eliminare la cartella, ma in realtà ho appena notato che montando il filesystem NTFS sotto Linux, la cartella risulta perfettamente accessibile:  
![screenshot](https://i.ibb.co/hg5X86b/oie-vrt29u8r-NIj-I.png)

**Comment by toto04** [comment]
Oof, grazie mille per la segnalazione!
Immagino proprio il problema sia dovuto al fatto che in una cartella il punto non dovrebbe essere un carattere legale, e per qualche ragione, nonostante il punto node, riesce comunque a creare la cartella invece di emettere un errore, molto strano.
In ogni caso provvederò a fare un pelo di test per esserne sicuro e sistemerò nella prossima versione.

**Comment by C0D3D3V** [comment]
Yes, periods and spaces at the end of filenames have always been a problem for Windows (see the last rule here: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions). There is no real reason for it (as you already found out yourself it works on Linux :D). There are also discrepancies between different filesystem interfaces, so it is sometimes possible to create files with forbidden names with one tool, but not be able to open them with another tool (e.g. Windows Explorer). I would recommend to use Linux instead of Windows ;)

Or sanitize the paths/filenames more strictly, I had decided to do that too (https://github.com/C0D3D3V/Moodle-Downloader-2/blob/ab4560de165e2e7a0a54e8fda1d5c1cf8d94b9dd/moodle_dl/download_service/path_tools.py#L14-L41).

**Comment by mind-overflow** [comment]
@toto04 figurati! Grazie a te per l'ottimo lavoro :) In teoria il problema lo dà solo il fatto che il punto sia alla fine del nome, perché ci sono altre cartelle con punti in mezzo che non danno problemi (e come infatti poi ha chiarito @C0D3D3V). Se ti serve una qualsiasi mano per testare dimmi pure! In ogni caso, a questo punto, personalmente credo che la cosa più sensata sia portare la sanificazione dei nomi da Moodle Downloader, sempre come ha spiegato @C0D3D3V...  
  
@C0D3D3V thanks for the in-depth explanation and links! And thank you too for the marvelous work with Moodle Downloader!  
> I would recommend to use Linux instead of Windows ;)  

Off-topic: I am actually running Arch Linux daily on both my desktop and laptop \:P However, I noticed this bug because I'm using a Surface tablet to take notes in class which only works fine on Windows!  
And actually, @toto04 is to blame here for not providing prebuilt binaries for Linux! Haha \:P

**Comment by toto04** [comment]
There is already a bit of sanitization where I noticed that the windows FS got angry at me, but definetly missed that trailing dot thing! Just microsoft being microsoft I guess ahah.
Also yes, once I fix this I absolutly need to look into providing binaries for linux, this negligence is unacceptable!
(and btw I too recommend linux instead of windows, as just a general rule of life ahah)

**Comment by mind-overflow** [comment]
Haha don't worry, I was just kidding about providing Linux binaries! I would definitely appreciate it, but don't feel forced if it's too much of a hassle or if you are busy with other stuff.

**Comment by toto04** [comment]
Ok should be fixed by pr #26 in the 0.8.0 release, but I couldn't find a course that had a folder with a trailing dot like the one you were reporting, so I haven't really tested the fix.
I'm positive it will work now, but just to be sure please try deleting the folder (in some way, I guess by using the mounted fs on linux lol), then update WeBeep Sync and download the folder again.
I'll wait on your feedback before closing this issue.

**Comment by mind-overflow** [comment]
Thanks for the quick fix! I tried v0.8.0 but, unfortunately, it's still happening. I also looked into the source code but couldn't find any issue - the regex works fine for any path ending in `./`. My only idea was that maybe, when the directory gets created, it doesn't have a trailing slash in the path (eg. `C:\path\to\folder` instead of `C:\path\to\folder\`) and thus the regex doesn't match it? I honestly don't know. Either way, thank you for your time and patience!

**Comment by toto04** [comment]
It just dawned on me that windows uses backwards slashes, I'm dumb lol 🤦‍♂️

I have added another regex with the backwards slashes that should fix the problem (famous last words), but to avoid making a new release before being sure the bug is fixed please try testing it by cloning the repo and starting the app from cmd (should be really easy, if you are not familiar with node just follow the run steps in the README)

Otherwise, if either the bug persists or if you are unable to test it, I think the easiest way to fix it would be if you just give me the course id so that I can subscribe to it from my webeep account and see what happens myself.

Also, thank _you_ for the patience, this is definitely creating way more problems than it should lol

**Comment by mind-overflow** [comment]
![success](https://i.ibb.co/z4ZGqHM/fixed.png)  
<br/> 
Success!!! Yeah, btw...  
> windows uses backwards slashes  
  
It was literally in front of my eyes too when I posted my last comment, where I proceeded to say "hey it parses fine `aaa./`!" and then "a typical windows path is `C:\folder\`"...  
  
Either way, thank you so much for being so quick! And, for future reference, I found a way to delete these kind of folders without having to boot on Linux and mount the volume. You just have to open an elevated PowerShell console and run this command:  
```powershell
rd /s "\\?\C:\Path\To\Folder."
```  
  
<br/>
Thanks again!
