### ISSUE TITLE
Add automatic updates

### ISSUE THREAD

**Issue by EndBug** [toto04/webeep-sync#28]
It would be nice if the app could update itself on patches and minor changes, so that you don't have to manually download the installer.
Then, for major versions (with breaking changes), it could still show the prompt as it's doing right now

**Comment by toto04** [comment]
You have no idea how much i want to implement this. Seriously.
Unfortunately to use electron's [autoUpdater](https://www.electronjs.org/docs/latest/api/auto-updater) the app must be signed, expecially on macOS apparently (it seems that on Windows this is not a strict requirement?), so I dont think I can actually do it until I manage to put my hands on an Apple Dev account 😢
More info about the audo updates here https://www.electronjs.org/docs/latest/tutorial/updates#handling-updates-manually

I have not really researched the possibility of implementing updates without the autoUpdater, I'm really not sure if that would circumvent the code-singing requirements. I'll look into it and if it turns out to be possible I'll make it work. 🤞
