### ISSUE TITLE
Sync error with zip files

### ISSUE THREAD

**Issue by simoneAmighini** [toto04/webeep-sync#30]
A file named "Raccolta temi esame.zip" causes a sync issue: every time the program updates webeep files, it downloads this file (which is exactly the same compared to the previous sync).

**Comment by toto04** [comment]
I'll be honest I have no idea about what would cause that to happen, also I personally have courses with zip files in them and did not encounter any issue 🤷‍♂️. Could you share the exact course that contains that file so that I can test it directly? Also just to check if it's a platform dependent issue, what OS are you running on?

**Comment by simoneAmighini** [comment]
WeBeep Sync is running on Windows 11. The course is "082742 - Elettrotecnica". Probably the issue is determined by 2 files named "Raccolta temi d'esame1.zip" and "Raccolta temi d'esame2.zip": even if they are different files they appeare to have the same name on the website. The program seems to read the name that appears and alternatively downloads one of the two files.
![WeBeep Sync Zip file Issue](https://user-images.githubusercontent.com/102897424/161483941-6157173f-6dae-414d-bad3-8364e29ab0a2.png)

**Comment by toto04** [comment]
Wow what an edge case! Thank you for reporting this issue, I'll investigate closely and see what would be the best behaviour to adopt.

Right now my guess is that each time a sync starts, webeep sync finds each of these files and sees that one is not the same as the one previously downloaded, so i think just alternates between them with each sync lol
